
- hosts: all  
  become: true
  vars:
    packages: ['docker.io', 'apparmor' ]
  tasks:
   - name: Set a hostname
     ansible.builtin.hostname:
        name: "{{ansible_hostname}}"
   - name: Update apt-cache
     apt: update_cache=yes
   - name: install packages
     apt:
       pkg:
       - docker.io
       - apparmor
       - python3-pip
   - name: Install pip3 docker
     pip:
        name:
          - docker
   - name: docker container for squeezelite
     docker_container:
        name: squeezelite
        image: giof71/squeezelite:stable
        state: started
        restart: yes
        restart_policy: always
        network_mode: host
        devices: /dev/snd:/dev/snd
        env: 
           SQUEEZELITE_NAME: "{{ansible_hostname}}" 
   - name: docker container for rhasspy
     docker_container:
        name: rhasspy 
        image: rhasspy/rhasspy
        state: started
        restart: yes
        restart_policy: always
        ports:
          - "12101:12101"
        devices: /dev/snd:/dev/snd
        volumes:
          - "{{ ansible_env.HOME }}/.config/rhasspy/profiles:/profiles"
          - "/etc/localtime:/etc/localtime:ro"
        command:  --user-profiles /profiles --profile ru

   - name: set max volume
     raw: amixer -c 0 set 'Line Out' 100% | amixer -c 0 set DAC 90%

